version: "3.9"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        restart: always
        ports:
            - "3000:5173"