version: "3.9"

services:
  backend:
    build:
      context: "backend/"
      dockerfile: "Dockerfile"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    ports:
      - "5555:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
        - "3000:5173"