version: "3.9"

services:
  s3server:
    image: scality/s3server:latest
    container_name: s3server
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SCALITY_ACCESS_KEY_ID=travel
      - SCALITY_SECRET_ACCESS_KEY=travel
      - SCALITY_CORS_ALLOW_ORIGIN=*
  s3server-test:
    image: scality/s3server:latest
    container_name: s3server-test
    restart: always
    ports:
      - "8001:8000"
    environment:
      - SCALITY_ACCESS_KEY_ID=travel
      - SCALITY_SECRET_ACCESS_KEY=travel
      - SCALITY_CORS_ALLOW_ORIGIN=*